### PR TITLE
Fix Android Build by removing jniLibs.srcDirs from android/build.gradle

### PR DESCRIPTION
**Pull request by cjroth**
I'm not 100% sure if this is something that affects everyone and should be merged into the actual repo or if it is due to some other libraries we are using, so I'd be cautious before you merge it.

### CODE REVIEW

**Comment by max-zu** [comment]
can this be merged and released ? thanks 🙏

**Comment by lyubo** [comment]
@max-zu when testing against react-native-sodium-example (plain react-native app with the only dependency react-native-sodium added) this PR leads to libsdoium.so not being included in the .apk file. Please do some investigation on your project/dependencies and take a look at the example application mentioned. Until the source of the error is found I cannot consider this one as a bug in react-native-sodium package.

**Comment by max-zu** [comment]
@lyubo what version of react-native did you use? I started to experience this issue after i updated RN in my project to 0.64

UPD: I investigated `react-native-sodium-example`. RN 0.63 has been user there. I think that issue might be related to bumped gradle plugin version 3.5.3 (RN.0.63) -> 4.1.0 (RN 0.64)

**Comment by max-zu** [comment]
@lyubo are there any updates regarding this issue ?

**Comment by arnaudambro** [comment]
@lyubo is it possible to merge this PR ?

**Comment by rap2hpoutre** [comment]
@lyubo Could you merge this PR please?

**Comment by gabimoncha** [comment]
PR was merged but not released

**Pull request merged**
