### PR TITLE
wrap crypto_pwhash

### PR DESCRIPTION
**Pull request by sfeese**
exposes crypto_pwhash and corresponding constants to js

### CODE REVIEW

**Comment by lyubo** [comment]
Thank you for your PR.

Just few notes:

You changed the definition of crypto_sign_keypair function  **RCTSodium.h**

Also, you removed the following line from **RCTSodiumModule.java**:
`constants.put("crypto_sign_BYTES", Sodium.crypto_sign_bytes());`

Are these commited by accident? If so please, create new PR with those two fixed.

Also, it would be very appreciated if you create a test for this function in corresponding [example project](https://github.com/lyubo/react-native-sodium-example).

**Comment by lyubo** [comment]
I just saw that  you don't release all arrays (**sodium-jni.c**).
Each `GetByteArrayElements` should have corresponding `ReleaseByteArrayElements`.
Please fix this!

**Comment by sfeese** [comment]
Thanks your review. I've fixed your comments.

**Comment by lyubo** [comment]
Thanks. Create new PR with the fixes, and I'll merge it.

**Pull request closed without merging**
