### PR TITLE
Build: use sha512sum instead of signature.

### LINKED ISSUE #32: Use the sha256sum (or whatever) of libsodium.tar.gz instead of the signature
Thanks for your great work.

I was thinking: why not use the sha256sum (or sha512sum, or whatever) instead of gpg? It removes the need for having gpg installed, the key imported and the tar.gz being different (but still signed with a valid key).

Thanks.

### PR DESCRIPTION
**Pull request by tasn**
When updating libsodium to a new version we just need to update the sha512 sum.
For example, the current file was generated with this command.
sha512sum libsodium-1.0.17.tar.gz > libsodium-1.0.17.tar.gz.sha512sum

Fixes #32 

Also fix how CURL is invoked for downloading the sources.

### CODE REVIEW

**Comment by lyubo** [comment]
Thanks, Tom.
Could you please, add  README file with corrected prerequisites to the same PR?

**Comment by tasn** [comment]
Updated. I removed the prerequisites for compilation as shasum should be available on Linux, Mac and etc.

**Comment by tasn** [comment]
Hey, just following up...

**Comment by tasn** [comment]
Thanks!

**Pull request merged**
